/* Generated By:JJTree: Do not edit this line. ASTMulti.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMulti extends SimpleNode {
  public ASTMulti(int id) {
    super(id);
  }

  public ASTMulti(AstParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d16be1825d2b5d401285ff3470fb7b04 (do not edit this line) */
