/* Generated By:JJTree: Do not edit this line. ASTOutput.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOutput extends SimpleNode {
  public ASTOutput(int id) {
    super(id);
  }

  public ASTOutput(AstParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1e3eec816df033b598f0fed9f2b66dba (do not edit this line) */
