/* Generated By:JavaCC: Do not edit this line. AstParserTreeConstants.java Version 7.0.10 */
public interface AstParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTASSIGN = 2;
  public int JJTINPUT = 3;
  public int JJTOUTPUT = 4;
  public int JJTADD = 5;
  public int JJTOPERATOR = 6;
  public int JJTMULTI = 7;
  public int JJTIDENT = 8;
  public int JJTVALUE = 9;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Assign",
    "Input",
    "Output",
    "Add",
    "Operator",
    "Multi",
    "Ident",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=3c7a4ad49f594622ee44ed6177e16311 (do not edit this line) */
