/* Generated By:JJTree: Do not edit this line. ASTAssign.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssign extends SimpleNode {
  public ASTAssign(int id) {
    super(id);
  }

  public ASTAssign(AstParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d09266b05ce563666d096c41b13bbbba (do not edit this line) */
