/* Generated By:JJTree: Do not edit this line. ASTInput.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInput extends SimpleNode {
  public ASTInput(int id) {
    super(id);
  }

  public ASTInput(AstParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9933bbb7c087be70e172bd320c0d946b (do not edit this line) */
