/* Generated By:JavaCC: Do not edit this line. AstParserTreeConstants.java Version 7.0.10 */
public interface AstParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTASSIGN = 2;
  public int JJTINPUT = 3;
  public int JJTOUTPUT = 4;
  public int JJTADD = 5;
  public int JJTOPERATOR = 6;
  public int JJTMULT = 7;
  public int JJTIDENT = 8;
  public int JJTVALUE = 9;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Assign",
    "Input",
    "Output",
    "Add",
    "Operator",
    "Mult",
    "Ident",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=2e76e9eb4685a80282f40b705edd70fb (do not edit this line) */
